apiVersion: batch/v1
kind: CronJob
metadata:
  name: minute-backup
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: minute-backup
        labels:
          app: minute-backup

        spec:
          containers:
          - name: backup-container
            image: busybox:1.28
            command:
            - /bin/sh
            - -c
            - >
              echo "Backup Started" ;
              mkdir -p /backups &&
              mkdir -p /demo-data &&
              cp -r /demp-data /backups &&
              echo "Backup Completed" ;
          restartPolicy: OnFailure
